### ISSUE TITLE
FSharp.Core dependency confusion

### ISSUE THREAD

**Issue by bartelink** [fsprojects/FsHttp#183]
14.4.1 specifies that the package depends on FSharp.Core v8
14.4.0 (and ones before that for quite a bit) omits it

Problem is that an app of mine had a `FSharp.Core ~> 7` in it's paket.dependencies.

Paket correctly says "well the latest I can give you is 14.4.0, which doesnt even require FSharp.Core`

**Comment by bartelink** [comment]
@SchlenkR Preparing a PR to downgrade FSharp.Core dep as much as possible on the basis that this triggers people updating FSharp.Core prematurely for no benefit (I tend to have my libs depend on 6.0.7 as it fixes a key Async.Parallel bug that can core dump the process)

Please let me know asp if you're not going to accept it...

**Comment by bartelink** [comment]
cc @dawedawe I see you added it; perhaps you have insight/preferences wrt the version?

**Comment by SchlenkR** [comment]
- FSharp.Core is pinned to 5.0.2 (>5 required for string interpolation; >5.0.2 required by FSharp.Data).
- Test projects (basically an application, targeting only the latest .Net version) don't reference FSharp.Core at all.
- No refs in build props!

Links: 

([Guidance for package authors](https://fsharp.github.io/fsharp-compiler-docs/fsharp-core-notes.html#Guidance-for-package-authors)

[Package authors should pin their FSharp.Core reference](https://fsharp.github.io/fsharp-compiler-docs/fsharp-core-notes.html#Package-authors-should-pin-their-FSharp-Core-reference)

**Hint:**

Instead of "Update", we use "Include" - don't ask me why, but that seems to work; update not.

I'll release **14.4.2** now...

**Comment by bartelink** [comment]
Thanks, this is great - packages / `paket update` passes the sniff test so closing.
Will report back here if there turns out to be any issues (not expecting any)
