### ISSUE TITLE
Content type 'text/json' should be 'application/json'

### ISSUE THREAD

**Issue by drhumlen** [fsprojects/FsHttp#93]
`application/json` is actually the correct type, not `text/json`. This actually caused the server I made http requests towards to fail because it didn't recognize `text/json` as a valid type.

**Comment by drhumlen** [comment]
https://github.com/fsprojects/FsHttp/pull/94

**Comment by ronaldschlenker** [comment]
According to [this post](https://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type), [RFC 4627](https://www.ietf.org/rfc/rfc4627.txt) and personal experience, the mime type of choice should indeed be `application/json` instead of `text/json`.

I will merge the linked PR. Since this might be a breaking change to some applications, this will be included in the next major release 7.

As a workaround, please have a look at the test [Explicitly specified content type is dominant](https://github.com/fsprojects/FsHttp/blob/49d47797a2d427489e0f8c8daa234ff8ccd4cc8d/src/Tests/Body.fs#L98), which shows how to force a specified content type.

Thanks for your issue and the PR, @drhumlen
